# Mysql
#   gem install mysql2
#
#   Ensure the mysql2 gem is defined in your Gemfile
#   gem 'mysql2
development:
  adapter: mysql2
  encoding: utf8
  database: colombo_dev
  pool: 5
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: colombo_test
  pool: 5
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: colombo_prod
  pool: 5
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock